# Generated by Django 4.1.2 on 2022-11-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Имя пользователя')),
                ('profile_pic', models.ImageField(upload_to='', verbose_name='Фото профиля')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('profile_type', models.CharField(max_length=2, verbose_name='Тип профиля')),
            ],
        ),
    ]
