# Generated by Django 4.1.2 on 2022-11-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('PE', 'Исполнитель'), ('CU', 'Заказчик'), ('CO', 'Консультант')], max_length=2, verbose_name='Тип профиля'),
        ),
    ]
