# Generated by Django 4.1.2 on 2022-11-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
