# Generated by Django 4.1.2 on 2022-11-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('PE', 'Исполнитель'), ('CU', 'Заказчик'), ('CO', 'Консультант')], max_length=2, verbose_name='Тип профиля'),
        ),
    ]
