# Generated by Django 4.1.2 on 2022-11-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_alter_profile_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_filled',
            field=models.BooleanField(default=False, verbose_name='Заполнен'),
        ),
    ]
