# Generated by Django 4.1.2 on 2022-11-05 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_profile_is_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^[_0-9a-zA-Z]{5,}$', 'Only alphanumeric characters and underscores are allowed.')], verbose_name='Имя пользователя в Telegram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk_username',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^[_0-9a-zA-Z]{5,}$', 'Only alphanumeric characters and underscores are allowed.')], verbose_name='Имя пользователя в VK'),
        ),
    ]
