# Generated by Django 4.1.2 on 2022-11-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_profile_telegram_username_profile_vk_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telegram_username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vk_username',
        ),
    ]
