# Generated by Django 4.1.2 on 2022-11-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_alter_profile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('PE', 'Исполнитель'), ('CU', 'Заказчик'), ('CO', 'Консультант')], max_length=2, verbose_name='Тип профиля'),
        ),
    ]
