# Generated by Django 4.1.2 on 2022-11-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_alter_profile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_images', verbose_name='Фото профиля'),
        ),
    ]
