# Generated by Django 4.1.2 on 2022-11-07 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0018_alter_profile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^[_0-9a-zA-Z]{5,}$', 'Только символы латинского алфавита, цифры и нижние подчеркивания разрешены')], verbose_name='Имя пользователя в Telegram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_username',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^[_0-9a-zA-Z]{5,}$', 'Только символы латинского алфавита, цифры и нижние подчеркивания разрешены')], verbose_name='Имя пользователя в VK'),
        ),
    ]
