# Generated by Django 4.1.2 on 2022-11-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RemoveField(
            model_name='card',
            name='looking_for',
        ),
        migrations.AddField(
            model_name='card',
            name='consultant',
            field=models.BooleanField(default=False, verbose_name='Консультант'),
        ),
        migrations.AddField(
            model_name='card',
            name='customer',
            field=models.BooleanField(default=False, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='card',
            name='partner',
            field=models.BooleanField(default=False, verbose_name='Напарник'),
        ),
        migrations.AddField(
            model_name='card',
            name='performer',
            field=models.BooleanField(default=False, verbose_name='Исполнитель'),
        ),
    ]
