# Generated by Django 4.1.2 on 2022-11-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_image_card_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
    ]
