# Generated by Django 4.1.2 on 2022-11-05 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_card_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('type_of_app', models.CharField(choices=[('RE', 'Исследование'), ('PR', 'Проект')], max_length=2, verbose_name='Тип приложения')),
                ('customer', models.BooleanField(default=False, verbose_name='Заказчик')),
                ('consultant', models.BooleanField(default=False, verbose_name='Консультант')),
                ('performer', models.BooleanField(default=False, verbose_name='Исполнитель')),
                ('partner', models.BooleanField(default=False, verbose_name='Напарник')),
                ('product_image', models.TextField(verbose_name='Образ продукта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
