# Generated by Django 4.1.2 on 2022-11-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_postcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
