# Generated by Django 4.1.2 on 2022-11-05 21:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_delete_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostCard',
            new_name='Card',
        ),
    ]
