# Generated by Django 4.1.2 on 2022-11-05 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_postcard_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
    ]
