# Generated by Django 4.1.2 on 2022-11-07 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_card_field_remove_card_type_of_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='card',
            name='field_of_card',
            field=models.CharField(choices=[('it', 'IT'), ('business', 'Бизнес'), ('design', 'Дизайн'), ('publishing', 'Издательское дело'), ('engineering', 'Инженерия'), ('media', 'Медиа'), ('education', 'Образование'), ('events', 'Организация событий'), ('oriental_studies', 'Востоковедение'), ('natural_sciences', 'Естественные науки'), ('art', 'Искусствоведение'), ('history', 'История'), ('culturology', 'Культурология'), ('marketing', 'Маркетинг'), ('maths', 'Математика'), ('management', 'Менеджмент'), ('linguistics', 'Лингвистика'), ('politics', 'Политология'), ('right', 'Право'), ('psychology', 'Психология'), ('sociology', 'Социология'), ('philology', 'Филология'), ('philosophy', 'Философия'), ('economy', 'Экономика')], max_length=20, verbose_name='Область'),
        ),
    ]
