# Generated by Django 4.1.2 on 2022-11-07 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_card_created_on_alter_card_field_of_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
    ]
